// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AppData.Infrastructures.Models;

public partial class Word
{
    public string Id { get; set; }

    public string Content { get; set; }

    public string BookTitle { get; set; }

    public string FirstLetter { get; set; }
}